### ISSUE TITLE
Please set the gripper's 'operating mode' to 'pwm' or 'current'

### ISSUE THREAD

**Issue by onePnot1** [tonyzhaozh/aloha#17]
Hi,

When I run `roslaunch aloha 4arms_teleop.launch`, I get four errors like `Please set the gripper's 'operating mode' to 'pwm' or 'current'`

Should I solve them or just ignore?

**Comment by sp-sophia-labs** [comment]
Hi, 

I have the same error after following the README. On my side it shows when running any execution script on the ALOHA. `python3 record_episodes.py` or `python3 one_side_teleop.py`. I have these two errors `Please set the group's 'profile type' to 'time'.` and `Please set the gripper's 'operating mode' to 'pwm' or 'current'.` triggering for each of the robots

I've been ignoring the issues with no problem so far

**Comment by onePnot1** [comment]
> Hi,
> 
> I have the same error after following the README. On my side it shows when running any execution script on the ALOHA. `python3 record_episodes.py`, `python3 one_side_teleop.py` or `python3 sleep.py`. I have these two errors `Please set the group's 'profile type' to 'time'.` and `Please set the gripper's 'operating mode' to 'pwm' or 'current'.` triggering for each of the robots
> 
> I have been ignoring these errors with no problem so far

Thanks a lot.
