### ISSUE TITLE
train

### ISSUE THREAD

**Issue by Nimingez** [tonyzhaozh/aloha#19]
For each timestep:
    observations
    - images
        - cam_high          (480, 640, 3) 'uint8'
        - cam_low           (480, 640, 3) 'uint8'
        - cam_left_wrist    (480, 640, 3) 'uint8'
        - cam_right_wrist   (480, 640, 3) 'uint8'
    - qpos                  (14,)         'float64'
    - qvel                  (14,)         'float64'
    
    action                  (14,)         'float64'
    """

    data_dict = {
        '/observations/qpos': [],
        '/observations/qvel': [],
        '/observations/effort': [],
        '/action': [],
    }
May I ask if qvel and effort are used in the training phase? What about in the inference phase? What would happen if qvel and effort are missing during the training phase?

**Comment by tonyzhaozh** [comment]
Hi,

qvel and effort are logged but we haven't tried including them in training/inference. Missing these fields should not matter at all.

Tony
