### ISSUE TITLE
May I ask whether this system is understood as an anti-interference teaching device？

### ISSUE THREAD

**Issue by haxx12113** [tonyzhaozh/aloha#2]
Hello, may I ask that this system can cope with interference, but there is no introduction of reinforcement learning in the paper, may I ask whether this is similar to the teaching device to demonstrate the playback of objects in accordance with the original teaching Angle? Instead of learning how to tie your shoes, play ping-pong, and thread in different directions?

**Comment by tonyzhaozh** [comment]
Yes this setup is designed for imitation learning (a more general "playback"). While it is certainly possible to run RL on ALOHA.

**Comment by ronjian** [comment]
Is it possible to train the model on the dataset which is collected from the camera+IMU device mounted on human arm?
