### ISSUE TITLE
Is there any training data?

### ISSUE THREAD

**Issue by luozhiping** [tonyzhaozh/aloha#20]
May I ask if there will be some training data available as a reference for training?

**Comment by tonyzhaozh** [comment]
They are released as part of RT-X (https://robotics-transformer-x.github.io/). We are planning to release it in a easier-to-access format in a month or two.

If you want to debug your code, I would recommend starting with ACT repo's sim environments. It has both scripted and human demonstrations readily available. The data format/training is exactly the same between sim and real.

Tony

**Comment by liangyuxin42** [comment]
Thanks for sharing! But in the shared [link](https://docs.google.com/spreadsheets/d/1rPBD77tk60AEIGZrGSODwyyzs5FgCU9Uz3h-3_t2A9g/edit#gid=0) I find that the Registered Dataset Name of ALOHA data is empty, and I failed to find the corresponding data of ALOHA from [RT-X dataset.](https://console.cloud.google.com/storage/browser/gresearch/robotics?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false) Is it possible to specify where I can download the ALOHA data? fe

**Comment by liangyuxin42** [comment]
Thanks for sharing! But in the shared [link](https://docs.google.com/spreadsheets/d/1rPBD77tk60AEIGZrGSODwyyzs5FgCU9Uz3h-3_t2A9g/edit#gid=0) I find that the Registered Dataset Name of ALOHA data is empty, and I failed to find the corresponding data of ALOHA from [RT-X dataset.](https://console.cloud.google.com/storage/browser/gresearch/robotics?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false) Is it possible to specify where I can download the ALOHA data?
