### ISSUE TITLE
How to set the current limit on a gripper using python api

### ISSUE THREAD

**Issue by DuaneNielsen** [tonyzhaozh/aloha#6]
Hey Tony,

Not an issue, feel free to close when you see it...

I read a comment in your code that you were trying to figure out how to set the current limit.

I chanced upon the solution, below...

I think you can get or set any register on the dynamixels using these ros services...

```
#!/usr/bin/env python

import rospy
from interbotix_xs_msgs.srv import RegisterValues


def service_command(service_path, cmd_type, name, reg, value=0):
    rospy.wait_for_service(service_path)

    try:
        get_registers = rospy.ServiceProxy(service_path, RegisterValues)

        # Make the service call
        response = get_registers(cmd_type, name, reg, value)

        # Process the response
        if response:
            print("Register values: ", response.values)
        else:
            print("Failed to get register values.")

    except rospy.ServiceException as e:
        print("Service call failed:", str(e))




if __name__ == '__main__':
    rospy.init_node('gripper_register_node')
    service_command('/puppet_left/get_motor_registers', 'single', 'gripper', 'Current_Limit')
    service_command('/puppet_left/set_motor_registers', 'single', 'gripper', 'Current_Limit', 800)
    service_command('/puppet_left/get_motor_registers', 'single', 'gripper', 'Current_Limit')
```

there is an equivalent ros command also, the form is something like...

```
rosservice call /puppet_left/get_motor_registers single gripper Hardware_Error_Status 0
```

**Comment by LSinterbotix** [comment]
You could also set `Current_Limit` (along with any other register EEPROM or RAM) on startup using a robot's [motor_config file](https://docs.trossenrobotics.com/interbotix_xsarms_docs/ros_interface/ros1/overview/xs_sdk.html#motor-configs-param-ros1).

For example, if you wanted to set `Current_Limit` on the ViperX-300s gripper motor, you would modify the [vx300s motor config](https://github.com/Interbotix/interbotix_ros_manipulators/blob/main/interbotix_ros_xsarms/interbotix_xsarm_control/config/vx300s.yaml) file like so:

```diff
  gripper:
    ID: 9
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255
+   Current_Limit: 800
```

**Comment by DuaneNielsen** [comment]
Also, here's another way to set a motor register on the gripper, using the Interbotix python API

```
puppet_bot = InterbotixManipulatorXS(robot_model="vx300s", group_name="arm", gripper_name="gripper", robot_name=f'puppet_{robot_side}', init_node=True)
puppet_bot.gripper.core.srv_set_reg('single', 'gripper', 'Current_Limit', 500)
```

Also, after using the robot and studying the API a bit more... I suspect you may have been intending to set the "Goal_Current" and not the "Current_Limit".  

When operating mode is "Current-based Position Control Mode", The "Goal_Current" register, will cause the gripper motor to limit the amount of current it uses.  This will ensure that the gripper motor applies no more than a maximum amount of torque to an object when it squeezes it.

"Current_Limit" will cause the motor to go into "Overload" state, reduce torque to zero and stop responding to further commands when more than the set amount of current is detected for a period of time.

So if we set Current_Limit to 300, we probably also should set the Goal_Current to a little less than 300.

I'm currently updating my clone with this config.  Let me know if this make sense to you.  Happy to send a PR if it turns out to be useful.

**Comment by MindFactoryAI** [comment]
Update to this one.  Here is how I'm currently setting the grippers, using the interbotix API...

puppet_bot = InterbotixManipulatorXS(robot_model="vx300s", group_name="arm", gripper_name="gripper",robot_name=f'puppet_{robot_side}', init_node=True)

The order of operations turns out to be important.

First we reboot the motors.
Then disable torque so we can set the current limit
Then set the current limit
Then set current based position mode.

I learned when current based position mode is set, torque will automatically be turned on.  So you cant set the operating mode then set the parameters.  You have to do the operations in the below order...

```
def reboot_grippers(puppet_bot_left, puppet_bot_right, current_limit=1000):

    for bot in [puppet_bot_left, puppet_bot_right]:
        bot.dxl.robot_reboot_motors("single", "gripper", True)
        bot.dxl.robot_torque_enable("single", "gripper", False)
        bot.dxl.robot_set_motor_registers("single", "gripper", 'Current_Limit', current_limit)
        bot.dxl.robot_set_operating_modes("single", "gripper", "current_based_position")
        bot.dxl.robot_torque_enable("single", "gripper", True)
```

**Comment by MindFactoryAI** [comment]
Also, I did some testing of the gripper motors, and as you mention in your instructions, setting current_limit to higher values than 300 causes overloading, even in current_based_position mode.  Whereas if it's set to 300, I observe no overloading.  Anyone reading this thread can verify this by placing an object in the gripper, then closing it using the dynamixel wizard with various current_limits.
